package System;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maneesha
 */

import java.sql.*;
import Objects.AdmissionObject;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {
    Start st; //declaring a variable to the Start Object.

    /**
     * Creates new form Login
     * @param st
     */
    public Login(Start st) {
        initComponents();
        this.st=st;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txp1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(3508, 2500));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");

        txt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        txp1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/green-back-button-icon-65921.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\manee\\Desktop\\forgot_password.png")); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txp1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        st.setVisible(true);    
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String t=txt1.getText(); //get the value of txt1 textfield to the t variable
        char[] p=txp1.getPassword(); //get the value of password field to a char array
        String r=String.valueOf(p);
        boolean flag = false;
            Statement s=Database.getStatement();
            try{
                String queryString="SELECT Username ,Password ,Position FROM employee"; //select the column names from the database
            try (ResultSet results = s.executeQuery(queryString)) {
                results.beforeFirst();
                //results.next();
                while (results.next()){
                    String staffname = results.getString("Username");
                    String password = results.getString("Password");
                    String position = results.getString("Position");
                    
                    if(t.equals(staffname)&& r.equals(password)){
                        
                        flag = true;
                        switch(position){ //switch statement
                            case "Nurse":
                                Nurse ad=new Nurse(this); //create a new Nurse object
                                //when a nurse login Nurse form will display
                                ad.setVisible(true);
                                this.dispose();
                                break;
                            case "Admin": 
                                MainSystem sys = new MainSystem(this); //system admin's form
                                sys.setVisible(true);
                                this.dispose();
                                Statement state = Database.getStatement(); 
                                ResultSet Rr = state.executeQuery("SELECT * FROM employee WHERE Username = '"+txt1.getText()+"'");
                                Rr.beforeFirst();   //when an admin login his personal details will be apear in the home page
                                Rr.next();
                                sys.jLabel4.setText(Rr.getString("ID"));
                                sys.jLabel6.setText(Rr.getString("Name"));
                                sys.jLabel8.setText(Rr.getString("NIC"));
                                sys.jLabel10.setText(Rr.getString("Address"));
                                sys.jLabel12.setText(Rr.getString("Gender"));
                                sys.jLabel14.setText(Rr.getString("DateOfBirth"));
                                sys.jLabel16.setText(Rr.getString("TelNo"));
                                sys.jLabel18.setText(Rr.getString("JoinedDate"));
                                Rr.close();
                                
                                
                                break;
                            case "Doctor":
                                Doctor doc=new Doctor(this);  //create new doctor object
                                doc.setVisible(true); //login to the doctor form
                                this.dispose();
                                
                                Statement stat = Database.getStatement();
                                ResultSet re = stat.executeQuery("SELECT * FROM employee WHERE Username = '"+txt1.getText()+"'");
                                re.beforeFirst();
                                re.next();
                                doc.jLabel10.setText(re.getString("Name"));
                                doc.jLabel12.setText(re.getString("Address"));
                                doc.jLabel14.setText(re.getString("TelNo"));
                                doc.jLabel16.setText(re.getString("DateOfBirth"));
                                doc.jLabel18.setText(re.getString("Age"));
                                doc.jLabel23.setText(re.getString("NIC"));
                                doc.jLabel20.setText(re.getString("Gender"));
                                doc.jLabel21.setText(re.getString("JoinedDate"));
                                doc.jLabel25.setText(re.getString("Username"));
                                doc.jLabel27.setText(re.getString("Password"));
                                re.close();
                                
                                Statement st = Database.getStatement();
                                ResultSet rs = st.executeQuery("SELECT * FROM doctor WHERE Employee_ID = (SELECT ID FROM employee WHERE Username = '"+txt1.getText()+"')");
                                rs.beforeFirst();;
                                rs.next();
                                doc.jLabel8.setText(rs.getString("id"));
                                doc.jLabel29.setText(rs.getString("Speciality"));
                                doc.jLabel31.setText(rs.getString("Qulifications"));
                                doc.jLabel33.setText(rs.getString("Ward_W_id"));
                                rs.close();
                                
                                Statement sta = Database.getStatement();
                                ResultSet rr = sta.executeQuery("SELECT Patient_ID FROM admission WHERE Doctor_id1 = (SELECT id FROM doctor WHERE Employee_ID = (SELECT ID FROM employee WHERE Username = '"+txt1.getText()+"'))");
                                rr.beforeFirst();
                                AdmissionObject adob = new AdmissionObject();
                                
                                DefaultListModel list = (DefaultListModel) doc.jList1.getModel();   //list model
                                
                                while(rr.next()){
                                    int patid = rr.getInt("Patient_ID");
                                    adob.setPatientid(patid);
                                    
                                    list.addElement(new Object[] {adob.getPatientid()});
                                }
                                
                                
                                break;
                                
                                
                                
                        }
                        
                        
                        
                        if(!flag){
                            JOptionPane.showMessageDialog(this,"Please check username and password","Employee Record",JOptionPane.INFORMATION_MESSAGE);
                            txt1.setText(null);
                            txp1.setText(null);
                            
                        }
                    }
                    
                }
            }
            }
            catch (SQLException sql){
                sql.printStackTrace();
            }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
              //  new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb5;
    public javax.swing.JPasswordField txp1;
    public javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
